accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path("create-profile/", views.CreateProfileView.as_view(), name="profile_create"),
    path('profile/', views.profile_view, name='profile'),
    path(
        "activate/<str:username>/<str:token>/",
        views.ActivateAccountView.as_view(),
        name="activate",
    ),
]

app_name = 'accounts'  # accounts:home

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG: # if we are working in mode Debug
#   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/nav/header.html
<header class="p-3 text-bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/static" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <a class="logo" href="https://www.djangoproject.com/">Django</a>
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink:href="#bootstrap"></use>
                </svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url "accounts:home" %}" class="nav-link px-2 text-secondary">Home</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..."
                       aria-label="Search">
            </form>

            <div class="text-end">
                {% if request.user.is_authenticated %}
                    <span><b>{{ request.user.get_full_name }}</b> ({{ request.user.username }})</span>
                    {% if request.user.profile %}
                        <a href="{% url 'accounts:profile' %}">
                            <img src="{{ request.user.profile.avatar.url }}"
                                 alt="{{ request.user.username }}'s avatar"
                                 width="25" height="25">
                        </a>
                    {% endif %}
                    <a class="text-decoration-none" href="{% url "accounts:logout" %}">
                        <button type="button" class="btn btn-outline-light me-2">Logout</button>
                    </a>
                {% else %}
                     <a class="text-decoration-none" href="{% url "accounts:login" %}">
                        <button type="button" class="btn btn-outline-light me-2">Login</button>
                    </a>
                    <a class="text-decoration-none" href="{% url "accounts:register" %}">
                        <button type="button" class="btn btn-warning">Sign-up</button>
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</header>